### PR TITLE
Added REST endpoint for uploading an artifact to a given App

### PR DESCRIPTION
**Pull request by phil-hei**
For a given App ID, an artifact can be uploaded to hawkbit

### CODE REVIEW

**Comment by phil-hei** [comment]
@trademkose Hi Adam, we added a REST endpoint for uploading an artifact for an existing app. Can you have a look? This is needed for connecting the IDE to the kuksa ecosystem and get rid of communicating with both appstore and hawkbit

**Comment by trademkose** [comment]
@phil-hei Hi Philipp. First of all thanks for your commit. It looks good but I have a concern about uploadArtifactFile(..) method in ArtifactFileEditor.java. The method that you wrote is similar with uploadArtifactFile(..) method in ArtifactFileEditor.java. 
So there are similar 2 method that do same job. 
I think we can move the uploadArtifactFile(..) method in ArtifactFileEditor.java to Appservice. 
So I think we need to edit and move the following method to Appservice and then we will envoke these methods from Appcontroller and ArtifactFileEditor.
_*private void deleteArtifact(Artifact artifact) 
*private void uploadArtifactFile(final String name, byte[] b)_

**Comment by phil-hei** [comment]
We more or less oriented at the uploadArtifactFile(..) method in ArtifactFileEditor.java. However, we had some concerns as there is a mixture of functionality and UI. So, you're basically right, the funtionality should be in AppService, whiel UI-related things should be in ArtifactFileEditor.
I'll have a look at that and try to untangle the corresponding code.

**Comment by phil-hei** [comment]
After some investigations, I see a big problem here. Within the appstore, Spring concepts (DI via @Autowired) and JVM managed Objects (via new()) are mixed up which lead that DI doesn't work anymore and one get a lot of NullPointer. 

The only way to solve this in a propper way would be to replace all objects created with new by @Autowired. However, this interference with some UI classes leading to other error messages. So, I'm actually not sure how to continue with that.

**Comment by eriksven** [comment]
Should we continue this discussion in a new issue? I could copy your text but I think it is better if @phil-hei opens the issue since he is more involved in the finding.

**Comment by phil-hei** [comment]
Created one here: https://github.com/eclipse/kuksa.cloud/issues/131

Should we reopen the PR (is it possible?)

**Pull request merged**
