### PR TITLE
adds support for event messages in connector

### LINKED ISSUE #172: connector should support Hono Event messages
The Hono InfluxDb Connector should also support the processing of Event messages. (Currently it supports telemetry messages but ignores events).

### PR DESCRIPTION
**Pull request by eriksven**
Adds support for event messages in connector. In that process the deprecated hono-client dependency is replaced with the newer hono-client-application-amqp dependency.

Closes #172

### CODE REVIEW

**Comment by eriksven** [comment]
This PR is based on the changes introduced in #171

**Review by bs-jokri — APPROVED** [review]
Checked and LGTM

**Comment by SebastianSchildt** [comment]
Should Jenkins be repaired before merge?

**Comment by eriksven** [comment]
Closing this PR as I came up with an alternative solution in #177

**Pull request closed without merging**
