### PR TITLE
Updated versions of some dependencies (Spring Boot to 2.1.0.RELEASE, …

### PR DESCRIPTION
**Pull request by eriksven**
Updated the dependencies for the pom.xml of the app store and added a license information.

### CODE REVIEW

**Comment by eriksven** [comment]
What do you think @trademkose? Can you test the changes. The update to Spring Boot 2.0.1.RELEASE would be helpful to make all sub-projects use the same Spring Boot version.

**Comment by eriksven** [comment]
see #72

**Comment by trademkose** [comment]
@eriksven I have tested the changes. Appstore works correctly. Your PR is acceptable for me. It can be merged. Thanks for your PR.

**Comment by eriksven** [comment]
@trademkose  thank you for the feedback

**Pull request merged**
