### PR TITLE
MariaDB integration, fixed AppView and other UI issues

### PR DESCRIPTION
**Pull request by fayvaz**

### CODE REVIEW

**Comment by rohoet** [comment]
Hi,

thanks for the PR!
I noticed you switched from H2 to MariaDB here.
mariadb-java-client is LGPL licensed that would only work as a *workswith* dependency for Eclipse, i.e., making MariaDB optional and not the prior solution the AppStore should work with.
Is there a chance you retain H2 as the default DB and make MariaDB optional?

Best regards,
Robert

**Comment by fayvaz** [comment]
Hi Robert –

Thanks for your comments and advice. We will look at this option.

Cheers,
-fatih

**Comment by fayvaz** [comment]
This pull request is closed due to mariadb-java-client dependency problem. When a "workswith" dependency implementation is ready, it will be reopened.

**Comment by fayvaz** [comment]
Thanks @bs-jokri . We are looking  this option. For now, we are back to H2 DBMS.

**Pull request closed without merging**
